development:
  adapter: mysql2
  database: exchange_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: exchange_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: exchange
  username: root
  password:
  host: localhost
